# Module: apache2
# Docs: https://www.elastic.co/guide/en/beats/filebeat/master/filebeat-module-apache2.html

- module: apache2
  # Access logs
  access:
    enabled: false

    # Set custom paths for the log files. If left empty,
    # Filebeat will choose the paths depending on your OS.
    var.paths:
      - /var/log/map3/access.log

  # Error logs
  error:
    enabled: true

    # Set custom paths for the log files. If left empty,
    # Filebeat will choose the paths depending on your OS.
    var.paths:
      - /var/log/map3/error.log
