name: "core-tile"

filebeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml
    reload.enabled: false

filebeat.overwrite_pipelines: true

filebeat.autodiscover:
  providers:
    - type: docker
      hints.enabled: true

# filebeat.inputs:
#   - type: log
#     paths:
#       - '/var/log/map3/*.log'
#       - '/var/log/nginx/*.log'

processors:
  - add_cloud_metadata: ~

output.logstash:
  codec.json:
    pretty: true
    escape_html: false
  hosts: ["logstash.map3.network:5044"]
  loadbalance: true
#output.logstash:
#  hosts: ["logstash.map3.network:5044"]
#  loadbalance: true

#output.elasticsearch:
#  hosts: '${ELASTICSEARCH_HOSTS:elasticsearch:9200}'
#  username: '${ELASTICSEARCH_USERNAME:}'
#  password: '${ELASTICSEARCH_PASSWORD:}'
