version: "2.3"

services:
  map3:
    build:
      context: ..
      dockerfile: map3-edge-in-docker/Dockerfile
    image: hyn/deploy-map3-edge:latest
    ports:
      - 80:80
      - 3000:3000
    restart: always
    privileged: true



