#metricbeat.config:
#  modules:
#    path: ${path.config}/modules.d/*.yml
    # Reload module configs as they change:
#    reload.enabled: false

metricbeat.autodiscover:
  providers:
    - type: docker
      hints.enabled: true

metricbeat.modules:
  - module: docker
    metricsets:
      - "container"
      - "cpu"
      - "diskio"
      - "healthcheck"
      - "info"
      #- "image"
      - "memory"
      - "network"
    hosts: ["unix:///var/run/docker.sock"]
    period: 1m
    processors:
      - drop_event.when.or:
          - regexp:
              container.image.name: "map3/heartbeat.*"
          - regexp:
              container.image.name: "map3/filebeat"
          - regexp:
              container.image.name: "map3/metricbeat.*"
          - regexp:
              container.image.name: "map3/logrotate.*"
          - regexp:
              container.image.name: "map3/ouroboros.*"
          - regexp:
              container.image.name: "map3/geostat.*"
          - regexp:
              container.image.name: "map3/grafana.*"
          - regexp:
              container.image.name: "map3/telegraf.*"
          - regexp:
              container.image.name: "map3/influxdb.*"
          - regexp:
              container.image.name: "map3/titan.*"
          - regexp:
              container.image.name: "map3/registry.*"
          - equals:
              container.image.name: "alpine:latest"
          - regexp:
              container.image.name: "map3/map3.*"
    enabled: true

processors:
  - add_cloud_metadata: ~

output.elasticsearch:
  hosts: ["422e2cc13f9d4a26a0bde7f53e7c4c55.ap-southeast-1.aws.found.io:9243"]
  protocol: "https"
  username: "metricbeat"
  password: "xQuqtk7lNyN9qebb"
  # using elastic search ingest geoip, one time setup to cluster
  # https://www.elastic.co/guide/en/elasticsearch/reference/7.1/geoip-processor.html
  pipeline: geoip
  #PUT _ingest/pipeline/geoip
  #  {
  #    "geoip": {
  #      "description": "Add geoip info",
  #      "processors": [
  #      {
  #        "geoip": {
  #          "field": "host.name",
  #          "target_field": "map3.geo",
  #          "ignore_failure": true
  #        }
  #      },
  #      {
  #        "geoip": {
  #          "field": "nginx.access.remote_ip",
  #          "target_field": "remote.geo",
  #          "ignore_failure": true
  #        }
  #      }
  #      ]
  #    }
  #  }
#  index: "metricbeat-%{[agent.version]}-%{+yyyy.MM}"

setup.template:
  name: "metricbeat"
  pattern: "metricbeat-*"
  enabled: false
#  overwrite: true

#setup.ilm.enabled: false
#https://github.com/elastic/beats/issues/11866