filebeat.overwrite_pipelines: true

filebeat.autodiscover:
  providers:
    - type: docker
      hints.enabled: true

filebeat.inputs:
  - type: log
    enable: true
    paths:
      - "/var/log/reverse-proxy/*.log"

processors:
  - add_cloud_metadata: ~

output.elasticsearch:
  username: filebeat
  password: l3OaUM&L3z#sbl*r
  protocol: https
  hosts: ["422e2cc13f9d4a26a0bde7f53e7c4c55.ap-southeast-1.aws.found.io:9243"]
  loadbalance: true
#output.logstash:
#  hosts: ["logstash.map3.network:5044"]
#  loadbalance: true

#output.elasticsearch:
#  hosts: '${ELASTICSEARCH_HOSTS:elasticsearch:9200}'
#  username: '${ELASTICSEARCH_USERNAME:}'
#  password: '${ELASTICSEARCH_PASSWORD:}'
