filebeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml
    reload.enabled: false

filebeat.overwrite_pipelines: true

filebeat.autodiscover:
  providers:
    - type: docker
      hints.enabled: true

processors:
  - add_cloud_metadata: ~

output.elasticsearch:
  hosts: ["422e2cc13f9d4a26a0bde7f53e7c4c55.ap-southeast-1.aws.found.io:9243"]
  protocol: "https"
  username: "filebeat"
  password: "l3OaUM&L3z#sbl*r"
  # using elastic search ingest geoip, one time setup to cluster
  # https://www.elastic.co/guide/en/elasticsearch/reference/7.1/geoip-processor.html
  pipeline: geoip